baseURL = "https://laroccadigitale.it/"
languageCode = "it"
title = "Marco La Rocca — Siti Web · Frascati"

[params]
  description = "Aiuto professionisti locali a essere visibili online. Su richiesta, realizzo siti web essenziali e curati per piccole attività a Frascati e nei Castelli Romani."
  author = "Marco La Rocca"

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# SEO
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
